GulsumKaymaz/urbanicFarm2

src/test/java/pages/WelcomePage.java
src/test/java/stepDefinitions/uiStepDef/Welcome/US063_Stepdefs.java
src/test/resources/features/uiFeatures/Welcome/US063.feature

US063 Created in 26/02/2023

---

src/test/java/stepDefinitions/uiStepDef/Orders/US062_stepDefs.java
src/test/java/stepDefinitions/uiStepDef/SellShareTrade/US042_StepDefs.java
src/test/resources/features/uiFeatures/Orders/US062.feature

user story 62 is working now

---

src/test/java/pages/OrdersPage.java
src/test/java/stepDefinitions/uiStepDef/Orders/US062_stepDefs.java

updating user story 62

---

src/test/java/pages/CommonPage.java
src/test/java/pages/Events.java
src/test/java/pages/EventsPage.java
src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/uiStepDef/Events/US072_stepDefs.java
src/test/java/stepDefinitions/uiStepDef/Welcome/US065_StepDefs.java
src/test/resources/features/uiFeatures/Events/US072.feature

US072 done with Rumeysa HOca and Sevinc Hoca and teacher Ezra  baskan

Ramazan-US072

---

src/test/java/pages/HomePage.java
src/test/java/stepDefinitions/uiStepDef/HomePage/US012_StepDefs.java

updated submit button

---

src/test/java/pages/EventsPage.java
src/test/resources/features/uiFeatures/Events/US078.feature

02/03/2023 US078 locators added to Framework by Said

02/03/2023 US078 locators added to Framework by Said

---

src/test/java/pages/WelcomePage.java
src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/uiStepDef/Welcome/US066_StepDefs.java
src/test/resources/features/uiFeatures/Welcome/US066.feature

Final Push Hakan 3.1.23

---

src/test/resources/features/uiFeatures/Events/US072.feature

US072 update

---

src/test/java/pages/EventsPage.java
src/test/java/stepDefinitions/uiStepDef/Events/US073_StepDefs.java
src/test/resources/features/uiFeatures/Events/US073.feature

sevinc_US_073 updated

---

src/test/java/pages/EventsPage.java
src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/uiStepDef/Events/US072_stepDefs.java
src/test/java/stepDefinitions/uiStepDef/Events/US078_StepDefs.java
src/test/resources/features/uiFeatures/Events/US072.feature
src/test/resources/features/uiFeatures/Events/US078.feature

US078 Created by Said in 04/03/2023

US078 Created by Said in 04/03/2023

---

src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/apiStepDef/Address.java
src/test/java/stepDefinitions/apiStepDef/US096_Stepdefs.java
src/test/resources/features/apiFeatures/US096.feature
src/test/resources/features/uiFeatures/Events/US078.feature

USO96 created by Said in 05/03/2023

USO96 created by Said in 05/03/2023

---

src/test/resources/features/apiFeatures/US096.feature

Small updates done in US078 & US096 by Said

Small updates done in US078 & US096 by Said

---

src/test/java/pages/EventsPage.java
src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/uiStepDef/Events/US077_stepDefs.java
src/test/resources/features/uiFeatures/Events/US077.feature

06.03.2023 US077 added Ugur

---

src/test/java/pages/EventsPage.java
src/test/java/stepDefinitions/uiStepDef/Events/US077_stepDefs.java
src/test/resources/features/uiFeatures/Events/US077.feature

07.03.2023 US077 update Ugur

---

src/test/java/runners/CukesRunner.java
src/test/resources/features/uiFeatures/DeliveryPickupSettings/US057.feature

i did not change anything

---

src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/uiStepDef/Orders/US062_stepDefs.java
src/test/java/utilities/Driver.java

Version problem resolved

---

src/test/java/stepDefinitions/apiStepDef/AllProducts.java
src/test/resources/features/apiFeatures/US097.feature

10.03.2023 ugur US097 added

---

src/test/java/runners/CukesRunner.java
src/test/java/stepDefinitions/apiStepDef/US093_StepDefs.java
src/test/java/stepDefinitions/uiStepDef/Events/US075_StepDefs.java
src/test/java/utilities/BrowserUtilities.java
src/test/resources/features/apiFeatures/US093.feature

Nida- 12.03.23- US093 edit, US075 updated

Nida- 12.03.23- US093 edit, US075 updated

---

src/test/java/stepDefinitions/apiStepDef/US082_StepDefs.java
src/test/java/stepDefinitions/apiStepDef/US088_StepDefs.java
src/test/java/stepDefinitions/apiStepDef/US103_StepDefs.java
src/test/java/stepDefinitions/apiStepDef/US104_StepDefs.java
src/test/resources/features/apiFeatures/US103.feature
src/test/resources/features/apiFeatures/US104.feature

sevinc US103,104

---

src/test/java/stepDefinitions/apiStepDef/US116_117_StepDefs.java
src/test/resources/features/apiFeatures/US116.feature

Gulsum US116_117 edited

---

src/test/java/stepDefinitions/apiStepDef/US107_StepDefs.java
src/test/resources/features/apiFeatures/US107.feature

US107 created By aziz 22.02.2023

US107 created By aziz 22.02.2023
